theme: jekyll-theme-slate
title: Gus's musing corner
description: my musings on security, leadership, and security leadership

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true
